# Generated by Django 5.0.3 on 2024-03-29 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NMS_sw', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='donor',
            table=None,
        ),
        migrations.AlterModelTable(
            name='student',
            table=None,
        ),
    ]
