# Generated by Django 5.0.3 on 2024-03-29 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NMS_sw', '0002_alter_donor_table_alter_student_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donor',
            old_name='number',
            new_name='Number',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='class_field',
            new_name='Grade',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='full_name',
            new_name='fullName',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='guardian_name',
            new_name='guardianName',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='performance_card',
            new_name='performance',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='school_name',
            new_name='schoolName',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='address',
        ),
    ]
