# Generated by Django 5.0.3 on 2024-03-29 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NMS_sw', '0004_alter_renewal_file_name_alter_student_performance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donor',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='donor',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='donor',
            old_name='password',
            new_name='Password',
        ),
    ]
