# Generated by Django 5.0.3 on 2024-03-29 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NMS_sw', '0005_rename_email_donor_email_rename_name_donor_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=120, null=True)),
                ('password', models.CharField(max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='estimations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sclass', models.PositiveIntegerField(null=True)),
                ('books', models.PositiveIntegerField(null=True)),
                ('uniforms', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='expenditure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='exphist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expe', models.PositiveIntegerField(null=True)),
                ('rec', models.CharField(max_length=801, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sclass', models.PositiveIntegerField(null=True)),
                ('books', models.PositiveIntegerField(null=True)),
                ('uniforms', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='totalmoney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sum', models.PositiveIntegerField(null=True, verbose_name='money')),
            ],
        ),
        migrations.RemoveField(
            model_name='renewal',
            name='File_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='password',
        ),
        migrations.AddField(
            model_name='donor_avail',
            name='books',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='donor_avail',
            name='donor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='NMS_sw.donor'),
        ),
        migrations.AddField(
            model_name='donor_avail',
            name='frequency',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='donor_avail',
            name='lastpaid',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='donor_avail',
            name='money',
            field=models.PositiveBigIntegerField(null=True, verbose_name='Rupees'),
        ),
        migrations.AddField(
            model_name='donor_avail',
            name='status',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='donor_avail',
            name='time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='donor_avail',
            name='ubstatus',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='donor_avail',
            name='uniform',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='renewal',
            name='session',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='books',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='money_needed',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='score',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='uniform',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='performance',
            field=models.FloatField(null=True),
        ),
        migrations.AlterModelTable(
            name='donor_avail',
            table=None,
        ),
        migrations.AlterModelTable(
            name='renewal',
            table=None,
        ),
    ]
