# Generated by Django 5.0.3 on 2024-03-29 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NMS_sw', '0006_admin_estimations_expenditure_exphist_inventory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='register_Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Number', models.CharField(max_length=15)),
                ('username', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('C_password', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='donor_avail',
            name='donor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='NMS_sw.register_donor'),
        ),
        migrations.DeleteModel(
            name='Donor',
        ),
    ]
