# Generated by Django 5.0.3 on 2024-03-30 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NMS_sw', '0007_register_donor_alter_donor_avail_donor_delete_donor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Renewal',
        ),
        migrations.RemoveField(
            model_name='register_donor',
            name='C_password',
        ),
    ]
